# Generated by Django 3.2.5 on 2021-07-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='media/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professions',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
