# Generated by Django 3.2.5 on 2021-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0002_auto_20210723_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
